### ISSUE TITLE
MY Community Pulldowns do not match with Master List of Lessons

### ISSUE THREAD

**Issue by dpentony** [MyCaert/Issues-Enhancements#149]
I went to post a couple of items to MY Community and noticed that the way the lessons are numbered in the MY Community pulldowns do not match with the the way they are listed in the master database. Here is an example:

When adding new lessons to MYcaert, we first add the lesson titles and numbers under Maintain Lessons. Below is a screenshot for lessons in the BMM library, Unit H, Problem Area 4. Notice that the Loan Language lesson is number BMM:H4.8.

![image](https://cloud.githubusercontent.com/assets/5790325/8916253/e741dfb2-346f-11e5-8a8d-bc0f6bb037a2.png)

However, when you go to the pulldowns when adding something to MY Community, that lesson shows up as BMM:H4.5. See screenshot below.

![image](https://cloud.githubusercontent.com/assets/5790325/8916309/4461220c-3470-11e5-8209-9d297b79d867.png)

The pulldowns for MY Community should be taking the titles and lesson numbers from the database we maintain under Maintain Lessons. That is the "master" list of lessons that we maintain as we add new lessons or edit their titles.

I also noticed the same thing when trying to add something in MY Community for Textiles and Design.

**Comment by bguerrettaz** [comment]
Ok, this took a bit to track down and debug, but I found the issue and have
resolved it.  Please test and confirm it is working as desired.

Thanks,
Blake

**Comment by dpentony** [comment]
I don't see any difference. When I go to add a post in MY Community the pull down still shows only five lessons in BMM: H4. I am trying to add a post for BMM:H4.8 - Loan Language. But the pull down does not list BMM:H4.8. The pull downs for MY Community are still not matching with what is in Maintain Lessons. Call me tomorrow if you want to discuss.

**Comment by bguerrettaz** [comment]
Sorry, I made this change for the search and forgot that it would be needed
in the share part as well.  I've made the same changes in the share part.
Please test and confirm.

Thanks,
Blake

**Comment by mnichols13** [comment]
some are ok, others I am seeing this error message:
![image](https://cloud.githubusercontent.com/assets/5790342/9060735/2812bb8a-3a7c-11e5-989d-8448fc70e95c.png)

**Comment by mnichols13** [comment]
This is the error:
ADODB.Field error '800a0bcd'
Either BOF or EOF is True, or the current record has been deleted. Requested operation requires a current record.
/Teachers/course-outlines/lesson-plan-library/Default.asp, line 617

**Comment by dpentony** [comment]
I see no difference. The pull down when you add something in MY Community still does not reflect the lesson numbers in the Master list of lessons. See edit/delete lessons under Maintain Lessons section. Lesson BMM: C4.8 is Loan Language. But, when you go to add a post to MY Community there is no lesson BMM:C4.8. The Loan Language lesson is listed as BMM:C4.5.

The lessons numbers and titles as they appear under Maintain Lessons is correct. This should drive what appears in the pull downs for MY Community.

**Comment by bguerrettaz** [comment]
Here is what I'm seeing from everything I've been doing.  When I look at
the admin console under maintain lessons, I see BMM:H4-8.  When I look at
MyCommunity search and add, I see the same things, which is reflected by
the changes I've made.

Please see below screen shots of all of my steps in analysis.

Sorry I can't call right now to go into more detail, hopefully this helps.



Maintain Lessons - Edit/Delete Lesson from Admin Console:

[image: Inline image 1]

MyCommunity Search:

[image: Inline image 2]

MyCommunity Add:

[image: Inline image 3]

MyCommunity Add Complete:

[image: Inline image 4]

**Comment by dpentony** [comment]
I can't see any of the images you posted. I guess you will have to call me when you have a chance.

P.S. Mindy had the same problem recently on another image you posted. She could not see it.

**Comment by bguerrettaz** [comment]
I've attached a word version of my email.

**Comment by dpentony** [comment]
I don't see an attachment.

**Comment by bguerrettaz** [comment]
![image](https://cloud.githubusercontent.com/assets/5695475/9062494/71947b84-3a88-11e5-895f-da51d1ed7c07.png)
![image](https://cloud.githubusercontent.com/assets/5695475/9062497/77d01aee-3a88-11e5-8b40-f32c20030607.png)
[EmailtoDanMindy_8.3.15.docx](https://github.com/MyCaert/Issues-Enhancements/files/1146/EmailtoDanMindy_8.3.15.docx)

**Comment by bguerrettaz** [comment]
Sorry, I'm replying from my GMail, which I guess doesn't include any of these items.  I'll start replying directly in GitHub.

**Comment by dpentony** [comment]
see my email and attachment

**Comment by bguerrettaz** [comment]
I see the problem. I only fixed the user side of the My Community, but I
also need to fix the admin side of MyCommunity.  I'll work on the admin
side as well and all should be fixed.

Make sense?

**Comment by dpentony** [comment]
Yes.

**Comment by bguerrettaz** [comment]
Ok, the admin side should also be fixed now.  Please confirm.

Blake

**Comment by dpentony** [comment]
Admin looks good. Thanks.
