### ISSUE TITLE
Current School Year report: State stds report: Quiz Report by student error message

### ISSUE THREAD

**Issue by mnichols13** [MyCaert/Issues-Enhancements#315]
When a teacher tries to view scores by student - this error message comes up

IL teacher Monica Pierce at Highland Community College
Quiz: Herbs - Biology Summer 2020
student: Jaidyn Alvarez

![image](https://user-images.githubusercontent.com/5790342/89559467-514c8380-d7db-11ea-94d6-5676cc4c6654.png)

**Comment by mnichols13** [comment]
The 2nd issue is this report - when you choose a course outline and it brings up all quizzes - it will not allow any exporting or sorting by student.

![image](https://user-images.githubusercontent.com/5790342/89582634-959d4b00-d7fe-11ea-9319-94600fca01e1.png)

**Comment by mnichols13** [comment]
any progress on this?

**Comment by bguerrettaz** [comment]
Hi - this should be resolved now.  I had to install/update the reportviewer
package and make the appropriate configuration changes.

Can you please test and confirm?

Thanks,
Blake

**Comment by mnichols13** [comment]
the group by student and export to MS word or MS excel still does not work. 

Go to Current School Year Report
Choose a course outline
A report will show by Quiz - but the other options bring up nothing.  The link to group by student or export does not function at all.
![image](https://user-images.githubusercontent.com/5790342/91091597-6cf9bb80-e61c-11ea-8920-3e46902265d1.png)

**Comment by mnichols13** [comment]
this was never fixed.  Is it possible to get this done?

**Comment by bguerrettaz** [comment]
Hi - the following had to be fixed:
- Word export
- Excel export
- Print function
- Group by student function

All were missing the Quiz Class reference and logic (not sure if it worked
before or how).

Please test and confirm.

Thanks,
Blake
